apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-event
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-event
  template:
    metadata:
      labels:
        app: backend-event
    spec:
      containers:
      - name: backend-event
        image: sarangasl/backend-event:latest
        imagePullPolicy: Always  # Forces K8s to pull your fresh code edits
        env:
        - name: PORT
          value: "3001"
        - name: MONGIDB_URI
          value: "mongodb+srv://saranga:saranga@cluster0.u9gdwrb.mongodb.net/event_registration"

        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: JWT_SECRET
        - name: MONGIDB_URI
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: MONGIDB_URI
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
                name: env-secrets
                key: NODE_ENV
        - name: SMTP_USER
          valueFrom:
              secretKeyRef:
                name: env-secrets
                key: SMTP_USER
        - name: SMTP_PASS
          valueFrom:
              secretKeyRef:
                name: env-secrets
                key: SMTP_PASS
        - name: SENDER_EMAIL
          valueFrom:
              secretKeyRef:
                name: env-secrets
                key: SENDER_EMAIL
        - name: CLOUD_NAME
          valueFrom:
              secretKeyRef:
                name: env-secrets
                key: CLOUD_NAME
        - name: CLOUD_API_KEY
          valueFrom:
              secretKeyRef:
                name: env-secrets
                key: CLOUD_API_KEY
        - name: CLOUD_API_SECRET
          valueFrom:
              secretKeyRef:
                name: env-secrets
                key: CLOUD_API_SECRET
        ports:
        - containerPort: 3001

        env:

---
apiVersion: v1
kind: Service
metadata:
  name: backend-event
spec:
  type: LoadBalancer
  selector:
    app: backend-event
  ports:
    -  protocol: TCP
       port: 80
       targetPort: 3001