apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-event
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-event
  template:
    metadata:
      labels:
        app: backend-event
    spec:
      containers:
      - name: backend-event
        image: sarangasl/backend-event:latest
        imagePullPolicy: Always  # Forces K8s to pull your fresh code edits
        env:
        - name: PORT
          value: "3001"
        - name: MONGIDB_URI
          value: "mongodb+srv://saranga:saranga@cluster0.u9gdwrb.mongodb.net/event_registration"

        ports:
        - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: backend-event
spec:
  type: LoadBalancer
  selector:
    app: backend-event
  ports:
    -  protocol: TCP
       port: 80
       targetPort: 3001