apiVersion: v1
kind: Secret
metadata:
  name: env-secrets
type: Opaque
data:
  JWT_SECRET: SECRET@123
  MONGIDB_URI: 'mongodb+srv://saranga:saranga@cluster0.u9gdwrb.mongodb.net/event_registration'
  NODE_ENV: production
  SMTP_USER: 911eab001@smtp-brevo.com
  SMTP_PASS: M7a04Up6t3DTs28v
  SENDER_EMAIL: sarangasama@gmail.com
  CLOUD_NAME: dadxdprtg
  CLOUD_API_KEY: 536637513617862
  CLOUD_API_SECRET: 8-0nlQ8IKU1j8oVg9LsvLqoEA8Q