name: Hello Backend App to Docker

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/**'
      - '.github/workflow/backend_Docker.yaml'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
